#pragma once

/*
 * Project-local switches for JC4880P443C / ESP32-P4 firmware experiments.
 *
 * This file is intentionally NOT generated by EEZ Studio and should survive
 * UI regeneration.  Keep board-specific guesses here so they can be changed
 * without digging through the implementation files.
 */

/*
 * Direct background orientation.
 *
 * EEZ works in a logical 800x480 landscape space while the ST7701/MIPI panel
 * native framebuffer is 480x800.  The direct renderer only rotates the full
 * background into the native framebuffer.  Do not mirror the full background
 * here by default: otherwise the user sees the photo jump/flip after page load.
 */
#ifndef P4_DIRECT_BG_MIRROR_Y_AFTER_ROTATE
#define P4_DIRECT_BG_MIRROR_Y_AFTER_ROTATE 0
#endif

#ifndef P4_DIRECT_BG_MIRROR_X_AFTER_ROTATE
#define P4_DIRECT_BG_MIRROR_X_AFTER_ROTATE 0
#endif

/*
 * LVGL redraws small rectangles under transparent/anti-aliased widgets.  The
 * full-screen direct background must remain untouched, but the LVGL crop that
 * is used only inside these widget redraw rectangles may need to be mirrored
 * so Arc/LED antialiasing samples pixels from the same logical place where
 * the widget ended up after EEZ/LVGL orientation correction.
 *
 * These two options affect ONLY the LVGL crop provider, not the visible
 * full-screen direct background.  Default is 0/0 because the style background
 * lives in the same LVGL logical 800x480 coordinate space as widgets; LVGL then
 * applies the same display rotation to widgets and crop rectangles.
 */

/*
 * Rotate the LVGL overlay/widget coordinate system by 180 degrees relative to
 * the previous working build.  The direct full-screen background renderer is
 * independent from this setting and remains untouched/fast.
 */
#ifndef P4_LVGL_ROTATE_UI_180_FROM_PREVIOUS
#define P4_LVGL_ROTATE_UI_180_FROM_PREVIOUS 1
#endif

#ifndef P4_LVGL_WIDGET_CROP_MIRROR_LR
#define P4_LVGL_WIDGET_CROP_MIRROR_LR 0
#endif

#ifndef P4_LVGL_WIDGET_CROP_MIRROR_TB
#define P4_LVGL_WIDGET_CROP_MIRROR_TB 0
#endif

#ifndef P4_ENABLE_LVGL_STYLE_CROP_PROVIDER
#define P4_ENABLE_LVGL_STYLE_CROP_PROVIDER 1
#endif

#ifndef P4_HIDE_DIRECT_BG_IMAGE_WHEN_OVERLAYS_EXIST
#define P4_HIDE_DIRECT_BG_IMAGE_WHEN_OVERLAYS_EXIST 1
#endif


/*
 * UI orientation contract.
 *
 * Single source of truth: EEZ/background logical space is 800x480 with
 * (0,0) at the top-left of the photo as it is shown in EEZ Studio.  Runtime
 * diagnostic widgets, LVGL overlay positions, touch mapping and LVGL crop
 * under transparent widget pixels must be kept synchronized against this
 * logical space.  The full-screen direct background renderer remains separate
 * and fast: it only copies/rotates the background into the native 480x800 LCD
 * framebuffer and must not be mirrored by overlay experiments.
 */
#ifndef P4_UI_LOGICAL_WIDTH
#define P4_UI_LOGICAL_WIDTH 800
#endif

#ifndef P4_UI_LOGICAL_HEIGHT
#define P4_UI_LOGICAL_HEIGHT 480
#endif

/*
 * Optional position-only mirroring for LVGL overlay objects.  This mirrors the
 * positions of top-level overlay objects inside the 800x480 logical page, but
 * does not mirror their pixels/text.  Keep both disabled for normal use; they
 * are diagnostic switches for orientation experiments.
 */
#ifndef P4_LVGL_WIDGET_POS_MIRROR_X
#define P4_LVGL_WIDGET_POS_MIRROR_X 0
#endif

#ifndef P4_LVGL_WIDGET_POS_MIRROR_Y
#define P4_LVGL_WIDGET_POS_MIRROR_Y 0
#endif

/*
 * Runtime FPS counter.  It is attached by the non-generated runtime layer and
 * anchored to the logical top-left of the background image.  Colors:
 *   < 30 FPS   red
 *   30..40 FPS yellow
 *   > 40 FPS   green
 */
#ifndef P4_ENABLE_FPS_COUNTER
#define P4_ENABLE_FPS_COUNTER 1
#endif

#ifndef P4_FPS_COUNTER_UPDATE_MS
#define P4_FPS_COUNTER_UPDATE_MS 500
#endif

#ifndef P4_FPS_COUNTER_X
#define P4_FPS_COUNTER_X 8
#endif

#ifndef P4_FPS_COUNTER_Y
#define P4_FPS_COUNTER_Y 8
#endif

/*
 * Static runtime overlay.  FPS and WiFi LED live on LVGL top layer instead of
 * being re-created per generated EEZ screen.  This keeps them in the same
 * logical place across page switches and lets us redraw them immediately after
 * the direct framebuffer background write.
 */
#ifndef P4_RUNTIME_OVERLAY_TOP_LAYER
#define P4_RUNTIME_OVERLAY_TOP_LAYER 1
#endif

/*
 * Direct runtime overlay.  FPS and WiFi LED are baked directly into the same
 * RGB565 framebuffer as the fast full-screen background, then periodically
 * refreshed as small native rectangles.  This avoids the visible erase/redraw
 * blink that happens when a LVGL top-layer widget is drawn after a direct
 * full-frame background write.
 */
#ifndef P4_DIRECT_RUNTIME_OVERLAY_ENABLE
#define P4_DIRECT_RUNTIME_OVERLAY_ENABLE 1
#endif

/* Keep LVGL copies of FPS/LED hidden by default.  The direct overlay is the
 * primary visible implementation.  Set to 1 only for comparison/debug. */
#ifndef P4_RUNTIME_OVERLAY_LVGL_VISIBLE
#define P4_RUNTIME_OVERLAY_LVGL_VISIBLE 0
#endif

#ifndef P4_DIRECT_FPS_BOX_W
#define P4_DIRECT_FPS_BOX_W 116
#endif

#ifndef P4_DIRECT_FPS_BOX_H
#define P4_DIRECT_FPS_BOX_H 22
#endif

#ifndef P4_DIRECT_SSID_BOX_X
#define P4_DIRECT_SSID_BOX_X (P4_FPS_COUNTER_X + P4_DIRECT_FPS_BOX_W + 8)
#endif

#ifndef P4_DIRECT_SSID_BOX_Y
#define P4_DIRECT_SSID_BOX_Y P4_FPS_COUNTER_Y
#endif

#ifndef P4_DIRECT_SSID_BOX_W
#define P4_DIRECT_SSID_BOX_W 340
#endif

#ifndef P4_DIRECT_SSID_BOX_H
#define P4_DIRECT_SSID_BOX_H P4_DIRECT_FPS_BOX_H
#endif

#ifndef P4_DIRECT_OVERLAY_BG_ALPHA
#define P4_DIRECT_OVERLAY_BG_ALPHA 72
#endif

#ifndef P4_DIRECT_OVERLAY_REFRESH_MS
#define P4_DIRECT_OVERLAY_REFRESH_MS P4_FPS_COUNTER_UPDATE_MS
#endif

#ifndef P4_DIRECT_INFO_STRIP_X
#define P4_DIRECT_INFO_STRIP_X 0
#endif

#ifndef P4_DIRECT_INFO_STRIP_Y
#define P4_DIRECT_INFO_STRIP_Y P4_FPS_COUNTER_Y
#endif

#ifndef P4_DIRECT_INFO_STRIP_W
#define P4_DIRECT_INFO_STRIP_W P4_UI_LOGICAL_WIDTH
#endif

#ifndef P4_DIRECT_INFO_STRIP_H
#define P4_DIRECT_INFO_STRIP_H P4_DIRECT_FPS_BOX_H
#endif

#ifndef P4_DIRECT_INFO_STRIP_RADIUS
#define P4_DIRECT_INFO_STRIP_RADIUS 0
#endif

#ifndef P4_DIRECT_INFO_STRIP_BORDER_ALPHA
#define P4_DIRECT_INFO_STRIP_BORDER_ALPHA 220
#endif

#ifndef P4_DIRECT_NET_TEXT_X
#define P4_DIRECT_NET_TEXT_X 140
#endif

#ifndef P4_DIRECT_FW_TEXT_X
#define P4_DIRECT_FW_TEXT_X 440
#endif

#ifndef P4_DIRECT_NET_TEXT_W
#define P4_DIRECT_NET_TEXT_W 280
#endif

#ifndef P4_DIRECT_FW_TEXT_W
#define P4_DIRECT_FW_TEXT_W (P4_UI_LOGICAL_WIDTH - P4_DIRECT_FW_TEXT_X - 8)
#endif

/*
 * ESP32-C6 programming/service pins.
 *
 * These are intentionally plain #defines.  Unknown lines are -1.  When the
 * real wiring is confirmed, change only this block, rebuild and flash P4.
 *
 * Direction names:
 *   P4_TX -> C6_U0RXD
 *   P4_RX <- C6_U0TXD
 *   C6_CHIP_PU behaves like EN/reset for the C6.
 *   C6_BOOT is normally C6_IO9 for ESP32-C6 UART download mode.
 */
#ifndef C6_PROG_UART_NUM
#define C6_PROG_UART_NUM 1
#endif

#ifndef C6_PROG_UART_BAUD
#define C6_PROG_UART_BAUD 115200
#endif

#ifndef C6_PROG_P4_TX_GPIO
#define C6_PROG_P4_TX_GPIO 29
#endif

#ifndef C6_PROG_P4_RX_GPIO
#define C6_PROG_P4_RX_GPIO 30
#endif

#ifndef C6_PROG_CHIP_PU_GPIO
#define C6_PROG_CHIP_PU_GPIO 33
#endif

#ifndef C6_PROG_BOOT_GPIO
#define C6_PROG_BOOT_GPIO 31
#endif

/*
 * When service backend is selected, this can leave the C6 in ROM UART
 * bootloader and bridge PC COM <-> C6 UART so esptool can talk to C6.
 */
#ifndef C6_PROG_ENABLE_TRANSPARENT_BRIDGE
#define C6_PROG_ENABLE_TRANSPARENT_BRIDGE 1
#endif

#ifndef C6_PROG_BRIDGE_AFTER_BOOTLOADER_PROBE
#define C6_PROG_BRIDGE_AFTER_BOOTLOADER_PROBE 1
#endif
